Repository ceph/ceph-container, pull requests merged in 2018-07, with the labels that each got.

#1119 zap_device: ability to zap partitions only
  src/daemon/zap_device.sh
Labels: backport-stable-3.0

#1131 tests: update python requirements
  tests/tox.sh
Labels: backport-stable-3.0

#1130 tests: update ceph-ansible requirements.txt picked up
  tests/tox.sh
Labels: backport

#1133 tests: update python requirements
  tests/tox.sh
Labels: backport

#1129 Backport of 1128 in stable-3.0
  src/daemon/disk_list.sh
Labels: backport

#1126 [skip ci] rgw: allow override RGW_FRONTENDS
  .travis.yml
  src/daemon/demo.sh
  src/daemon/start_rgw.sh
  src/daemon/variables_entrypoint.sh
Labels: backport-stable-3.0, backport-stable-3.1

#1136 [skip ci] rhel7: make Dockerfile linting happy
  ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__
  ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_PREINSTALL__
Labels: backport-stable-3.1
