Repository ceph/ceph-container, pull requests merged in 2019-10, with the labels that each got.

#1489 src/daemon-base: add smartmontools and nvme-cli packages
  src/daemon-base/__CEPH_BASE_PACKAGES__
Labels: enhancement

#1490 src/daemon-base: add smartmontools and nvme-cli packages (bp #1489)
  src/daemon-base/__CEPH_BASE_PACKAGES__
Labels: backport-stable-4.0

#1488 ubi8: use quotes for LABEL version
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_PREINSTALL__
Labels: backport-stable-4.0, enhancement

#1491 ubi8: use quotes for LABEL version
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_PREINSTALL__
Labels: backport-stable-4.0

#1496 src/daemon-base: add libstoragemgmt
  src/daemon-base/__CEPH_BASE_PACKAGES__
Labels: backport-stable-4.0

#1497 src/daemon: enforce ceph-osd ulimit values
  ceph-releases/luminous/daemon/osd_scenarios/osd_disk_activate.sh
  ceph-releases/mimic/daemon/osd_scenarios/osd_disk_activate.sh
  src/daemon/osd_scenarios/osd_disk_activate.sh
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-3.2, backport-stable-4.0, bug

#1498 centos: Add silent option to curl commands
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: enhancement

#1499 src/daemon: enforce ceph-osd ulimit values (bp #1497)
  src/daemon/osd_scenarios/osd_disk_activate.sh
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-4.0

#1500 src/daemon: enforce ceph-osd ulimit values (bp #1497)
  src/daemon/osd_scenarios/osd_disk_activate.sh
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-3.2

#1501 Makefile: add docker pull parameter on build
  src/daemon-base/Makefile
Labels: backport-stable-3.2, backport-stable-4.0, enhancement

#1502 Makefile: add docker pull parameter on build (bp #1501)
  src/daemon-base/Makefile
Labels: backport-stable-4.0

#1503 Makefile: add docker pull parameter on build (bp #1501)
  src/daemon-base/Makefile
Labels: backport-stable-3.2
