Repository ceph/ceph-container, pull requests merged in 2019-04, with the labels that each got.

#1339 travis: Remove image push to docker hub
  .travis.yml
Labels: enhancement

#1342 base: fix lang.sh removal on RHEL
  ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
  ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
Labels: backport-stable-4.0, bug

#1337 base: add packages for ceph-csi
  src/daemon-base/__CEPH_BASE_PACKAGES__
  src/daemon-base/__CSI_PACKAGES__
Labels: enhancement

#1344 With dmcrypt expect /dev/mapper/device to be used
  src/daemon/osd_scenarios/osd_disk_activate.sh
Labels: bug

#1345 contrib: Add alpha/beta tag filtering
  contrib/build-push-ceph-container-imgs.sh
Labels: bug

#1348 daemon-base: Add ceph point release to csi pkgs
  src/daemon-base/__CSI_PACKAGES__
Labels: bug

#1347 contrib/ceph-build-config.sh: Fix version sort
  contrib/ceph-build-config.sh
Labels: bug

#1350 daemon-base: Add ceph-mgr-diskprediction-local pkg
  src/daemon-base/__CEPH_MGR_PACKAGE__
Labels: backport-stable-4.0, enhancement

#1340 travis: Remove civetweb references for demo
  .travis.yml
  src/daemon/demo.sh
Labels: enhancement

#1351 daemon-base: Add ceph-mgr-diskprediction-local pkg
  src/daemon-base/__CEPH_MGR_PACKAGE__
Labels: backport-stable-4.0

#1352 rhel8: rm ubi.repo
  ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_PREINSTALL__
Labels: backport-stable-4.0

#1353 rhel8: rm ubi.repo
  ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_PREINSTALL__
Labels: backport-stable-4.0

#1354 daemon: Fix mds permissions to client.admin
  src/daemon/config.kv.etcd.sh
  src/daemon/config.static.sh
Labels: backport-stable-3.2, bug

#1357 osd_disk_prepare: Don't always create db and wal
  src/daemon/osd_scenarios/osd_disk_prepare.sh
Labels: bug
