Repository ceph/ceph-container, pull requests merged in 2019-05, with the labels that each got.

#1365 rhel8: drop "-rhel8" from component label
  ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_PREINSTALL__
Labels: backport-stable-4.0

#1367 contrib: compose-rhcs for nautilus + RHEL 8
  contrib/compose-rhcs.sh
Labels: backport-stable-4.0

#1368 contrib/commit-rhcs.sh: Nautilus on RHEL 8
  contrib/commit-rhcs.sh
Labels: enhancement

#1369 contrib/commit-rhcs.sh: Nautilus on RHEL 8
  contrib/commit-rhcs.sh
Labels: backport-stable-4.0, enhancement

#1372 rhel8: use production content-sets
  ceph-releases/ALL/rhel8/daemon/content_sets.yml
Labels: backport-stable-4.0

#1376 ceph-disk: fix dmcrypt with bluestore db/wal
  src/daemon/common_functions.sh
Labels: backport-stable-3.2, bug

#1375 Fix monmap_command for MON_HEALTH daemon
  src/daemon/check_zombie_mons.py
Labels: backport-stable-3.2, backport-stable-4.0, bug

#1377 ceph-disk: fix dmcrypt with bluestore db/wal
  src/daemon/common_functions.sh
Labels: backport-stable-3.2

#1378 Fix monmap_command for MON_HEALTH daemon
  src/daemon/check_zombie_mons.py
Labels: backport-stable-4.0

#1379 Fix monmap_command for MON_HEALTH daemon
  src/daemon/check_zombie_mons.py
Labels: backport-stable-3.2

#1386 rhel8: rebase image on ubi8
  ceph-releases/ALL/ubi8/__DOCKERFILE_CLEAN_COMMON__
  ceph-releases/ALL/ubi8/__DOCKERFILE_MAINTAINER__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_PREINSTALL__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_VERIFY_PACKAGES__
  ceph-releases/ALL/ubi8/daemon-base/__ISCSI_PACKAGES__
  ceph-releases/ALL/ubi8/daemon-base/__RADOSGW_PACKAGES__
  ceph-releases/ALL/ubi8/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/ubi8/daemon/__DOCKERFILE_POSTINSTALL_CLEANUP__
  ceph-releases/ALL/ubi8/daemon/__DOCKERFILE_PREINSTALL__
  ceph-releases/ALL/ubi8/daemon/__DOCKERFILE_VERIFY_PACKAGES__
  ceph-releases/ALL/ubi8/daemon/content_sets.yml
  ceph-releases/ALL/ubi8/daemon/disabled_scenario
  contrib/commit-rhcs.sh
  contrib/compose-rhcs.sh
Labels: backport-stable-4.0, enhancement

#1389 rhel8: rebase image on ubi8
  ceph-releases/ALL/ubi8/__DOCKERFILE_CLEAN_COMMON__
  ceph-releases/ALL/ubi8/__DOCKERFILE_MAINTAINER__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_PREINSTALL__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_VERIFY_PACKAGES__
  ceph-releases/ALL/ubi8/daemon-base/__ISCSI_PACKAGES__
  ceph-releases/ALL/ubi8/daemon-base/__RADOSGW_PACKAGES__
  ceph-releases/ALL/ubi8/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/ubi8/daemon/__DOCKERFILE_POSTINSTALL_CLEANUP__
  ceph-releases/ALL/ubi8/daemon/__DOCKERFILE_PREINSTALL__
  ceph-releases/ALL/ubi8/daemon/__DOCKERFILE_VERIFY_PACKAGES__
  ceph-releases/ALL/ubi8/daemon/content_sets.yml
  ceph-releases/ALL/ubi8/daemon/disabled_scenario
  contrib/commit-rhcs.sh
  contrib/compose-rhcs.sh
Labels: backport-stable-4.0
