Repository ceph/ceph-container, pull requests merged in 2019-12, with the labels that each got.

#1530 ceph-build-config: fix infinite loop on registry
  contrib/ceph-build-config.sh
Labels: bug

#1531 daemon-base: add ceph-mgr-k8sevents package
  ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
  src/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-4.0

#1532 daemon-base: add ceph-mgr-k8sevents package (bp #1531)
  ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
  src/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-4.0

#1538 daemon: handle special devices in dmcrypt data
  src/daemon/common_functions.sh
Labels: backport-stable-3.2, enhancement

#1539 daemon: handle special devices in dmcrypt data (bp #1538)
  src/daemon/common_functions.sh
Labels: backport-stable-3.2

#1541 Revert "nfs: run a dedicated dbus daemon for nfs-ganesha"
  src/daemon/start_nfs.sh
Labels: backport-stable-3.2, backport-stable-4.0, bug

#1537 daemon: speed up create_mandatory_directories
  src/daemon/common_functions.sh
Labels: backport-stable-3.2, backport-stable-4.0, enhancement

#1542 Revert "nfs: run a dedicated dbus daemon for nfs-ganesha" (bp #1541)
  src/daemon/start_nfs.sh
Labels: backport-stable-4.0

#1543 Revert "nfs: run a dedicated dbus daemon for nfs-ganesha" (bp #1541)
  src/daemon/start_nfs.sh
Labels: backport-stable-3.2

#1544 daemon: speed up create_mandatory_directories (bp #1537)
  src/daemon/common_functions.sh
Labels: backport-stable-4.0

#1545 daemon: speed up create_mandatory_directories (bp #1537)
  src/daemon/common_functions.sh
Labels: backport-stable-3.2

#1546 contrib: support two digits z release
  contrib/build-push-ceph-container-imgs.sh
Labels: enhancement
