Repository ceph/ceph-container, pull requests merged in 2019-07, with the labels that each got.

#1410 daemon/start_mon.sh: add mon without port value
  src/daemon/start_mon.sh
Labels: backport-stable-4.0, bug

#1412 daemon/start_mon.sh: add mon without port value (bp #1410)
  src/daemon/start_mon.sh
Labels: backport-stable-4.0

#1414 Makefile: disable openSUSE 42.3 luminous build (bp #1390)
  Makefile
Labels: backport-stable-4.0

#1415 Makefile: disable openSUSE 42.3 luminous build (bp #1390)
  Makefile
Labels: backport-stable-3.2

#1411 Add CEPH_DEVEL flag for using ceph devel packages
  Makefile
  README.md
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  contrib/build-push-ceph-container-imgs.sh
  maint-lib/makelib.mk
  maint-lib/stage.py
  maint-lib/stagelib/envglobals.py
  src/STAGING_ENV_VARS.md
  src/daemon-base/Dockerfile
Labels: enhancement

#1419 contrib: Update ceph nano to v2.3.1
  contrib/build-push-ceph-container-imgs.sh
Labels: enhancement

#1418 Makefile: Update flavors for stable-3.2
  Makefile
Labels: enhancement

#1417 Makefile: Update flavors for stable-4.0
  Makefile
Labels: enhancement

#1416 contrib: override releases list on stable branch
  contrib/build-push-ceph-container-imgs.sh
Labels: enhancement

#1424 centos: Enable and update NFS Ganesha
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__GANESHA_PACKAGES__
Labels: enhancement

#1428 zap_device: zap dmcrypt partitions as well (bp #1425)
  src/daemon/zap_device.sh
Labels: backport-stable-3.2, bug

#1425 zap_device: zap dmcrypt partitions as well
  src/daemon/zap_device.sh
Labels: backport-stable-3.2, backport-stable-4.0

#1427 zap_device: zap dmcrypt partitions as well (bp #1425)
  src/daemon/zap_device.sh
Labels: backport-stable-4.0, bug

#1426 Dockerfile: update maintainer name
  ceph-releases/ALL/centos/__DOCKERFILE_MAINTAINER__
  ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__
  ceph-releases/ALL/ubi8/__DOCKERFILE_MAINTAINER__
  src/__DOCKERFILE_MAINTAINER__
Labels: backport-stable-3.2, backport-stable-4.0

#1429 Dockerfile: update maintainer name (bp #1426)
  ceph-releases/ALL/centos/__DOCKERFILE_MAINTAINER__
  ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__
  ceph-releases/ALL/ubi8/__DOCKERFILE_MAINTAINER__
  src/__DOCKERFILE_MAINTAINER__
Labels: backport-stable-4.0

#1430 Dockerfile: update maintainer name (bp #1426)
  ceph-releases/ALL/centos/__DOCKERFILE_MAINTAINER__
  ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__
  src/__DOCKERFILE_MAINTAINER__
Labels: backport-stable-3.2

#1431 daemon/common_functions.sh: remove NBSP
  .travis.yml
  src/daemon/common_functions.sh
Labels: backport-stable-3.2, backport-stable-4.0, bug

#1432 daemon/common_functions.sh: remove NBSP (bp #1431)
  .travis.yml
Labels: backport-stable-4.0

#1433 daemon/common_functions.sh: remove NBSP (bp #1431)
  .travis.yml
  src/daemon/common_functions.sh
Labels: backport-stable-3.2

#1438 nautilus: pin ganesha version to 2.8 (bp #1435)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0, enhancement

#1440 config.kv.etcd: Remove set-uid flag for nautilus+
  src/daemon/config.kv.etcd.sh
Labels: backport-stable-4.0, bug

#1441 config.kv.etcd: Remove set-uid flag for nautilus+ (bp #1440)
  src/daemon/config.kv.etcd.sh
Labels: backport-stable-4.0
