Repository ceph/ceph-container, pull requests merged in 2019-11, with the labels that each got.

#1506 centos: run pip after rpm package installation
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: bug

#1514 demo: move OSD data path in dedicated section
  src/daemon/demo.sh
Labels: enhancement

#1516 ubi8: add container.yaml
  ceph-releases/ALL/ubi8/daemon/container.yaml
Labels: enhancement

#1517 nfs: run a dedicated dbus daemon for nfs-ganesha
  src/daemon/start_nfs.sh
Labels: backport-stable-3.2, backport-stable-4.0, enhancement

#1518 nfs: run a dedicated dbus daemon for nfs-ganesha (bp #1517)
  src/daemon/start_nfs.sh
Labels: backport-stable-4.0

#1519 nfs: run a dedicated dbus daemon for nfs-ganesha (bp #1517)
  src/daemon/start_nfs.sh
Labels: backport-stable-3.2

#1524 ubi8: add ceph-mgr-k8sevents package
  ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-4.0, enhancement

#1525 ubi8: add ceph-mgr-k8sevents package (bp #1524)
  ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-4.0

#1526 ubi8: remove ceph-mgr-ssh package
  ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-4.0, bug

#1527 ubi8: remove ceph-mgr-ssh package (bp #1526)
  ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-4.0
