Repository ceph/ceph-container, pull requests merged in 2019-06, with the labels that each got.

#1381 contrib/build-push-ceph: Add arm64 for nautilus
  Makefile
  contrib/build-push-ceph-container-imgs-arm64.sh
  contrib/build-push-ceph-container-imgs.sh
Labels: enhancement

#1390 Makefile: disable openSUSE 42.3 luminous build
  Makefile
Labels: bug

#1391 populate_kv.sh: create client_host directory once
  src/daemon/populate_kv.sh
Labels: enhancement

#1394 daemon-base: Use nfs-ganesha 2.8 for nautilus
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/luminous/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/mimic/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: enhancement

#1398 daemon: create log directories for rbd target
  src/daemon/start_rbd_target_api.sh
  src/daemon/start_rbd_target_gw.sh
Labels: bug

#1407 centos/daemon-base: merge __DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/luminous/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/mimic/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: enhancement

#1408 variables_entrypoint.sh: improve logging
  src/daemon/config.static.sh
  src/daemon/variables_entrypoint.sh
Labels: backport-stable-4.0, enhancement
