Repository ceph/ceph-container, pull requests merged in 2019-03, with the labels that each got.

#1328 daemon: Add support for python3
  src/daemon/demo.sh
  src/daemon/osd_scenarios/osd_directory_single.sh
  src/daemon/osd_scenarios/osd_volume_activate.sh
  src/daemon/variables_entrypoint.sh
  src/daemon/watch_mgr_health.sh
Labels: bug

#1332 daemon/variables_entrypoint Fix python detection
  ceph-releases/luminous/daemon/variables_entrypoint.sh
  ceph-releases/mimic/daemon/variables_entrypoint.sh
  src/daemon/variables_entrypoint.sh
Labels: bug

#1334 osd_disk_activate: Use python binary variable
  src/daemon/osd_scenarios/osd_disk_activate.sh
Labels: bug

#1335 daemon: Fix mds permissions to client.admin
  ceph-releases/luminous/daemon/config.static.sh
  ceph-releases/mimic/daemon/config.static.sh
  src/daemon/config.kv.etcd.sh
  src/daemon/config.static.sh
Labels: bug

#1336 base: remove lang.sh
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
  ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
  ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
Labels: enhancement

#1338 [skip ci] contrib: Do not show HEAD ref in git ls-remote
  contrib/build-push-ceph-container-imgs.sh
Labels: bug

#1341 base: fix lang.sh removal on RHEL
  ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
  ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
Labels: backport-stable-4.0, bug
