Repository ceph/ceph-container, pull requests merged in 2019-09, with the labels that each got.

#1472 fix: assign properly OSD_DISKS variable
  src/daemon/osd_scenarios/osd_disks.sh
Labels: bug

#1483 osd_volume_activate: handle loop device
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-4.0, bug

#1482 osd_disk_activate: resolve device symlink
  src/daemon/osd_scenarios/osd_disk_activate.sh
Labels: backport-stable-4.0, bug

#1474 fix: delete temporary mount point
  src/daemon/disk_list.sh
Labels: enhancement
