Repository ceph/ceph-container, pull requests merged in 2020-11, with the labels that each got.

#1729 DAEMON_OPTS: use --default-* for logging opts
  src/daemon/start_mon.sh
  src/daemon/variables_entrypoint.sh
Labels: backport-stable-4.0, backport-stable-5.0

#1740 [skip ci] contrib: registry login earlier
  contrib/build-ceph-base.sh
  contrib/ceph-build-config.sh
Labels: enhancement

#1749 DAEMON_OPTS: use --default-* for logging opts (bp #1729)
  src/daemon/start_mon.sh
  src/daemon/variables_entrypoint.sh
Labels: backport-stable-5.0

#1750 DAEMON_OPTS: use --default-* for logging opts (bp #1729)
  src/daemon/start_mon.sh
  src/daemon/variables_entrypoint.sh
Labels: backport-stable-4.0

#1754 tests/tox: consume docker registry credentials
  tests/tox.sh
Labels: enhancement, tests

#1756 centos/8: add python3-saml package
  ceph-releases/ALL/centos/8/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-5.0, enhancement

#1758 centos/8: add python3-saml package (bp #1756)
  ceph-releases/ALL/centos/8/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-5.0
