Repository ceph/ceph-container, pull requests merged in 2020-03, with the labels that each got.

#1600 ubi8: add gating.yaml
  ceph-releases/ALL/ubi8/daemon/gating.yaml
Labels: backport-stable-4.0, enhancement

#1601 ubi8: add gating.yaml (bp #1600)
  ceph-releases/ALL/ubi8/daemon/gating.yaml
Labels: backport-stable-4.0

#1602 rhel7: add gating.yaml (bp #1600)
  ceph-releases/ALL/rhel7/daemon/gating.yaml
Labels: backport-stable-3.2

#1609 Add ceph octopus release
  .travis.yml
  Makefile
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  contrib/build-push-ceph-container-imgs.sh
Labels: enhancement

#1610 contrib: add missing octopus condition
  contrib/build-push-ceph-container-imgs.sh
Labels: bug

#1613 tox: update ansible release
  tox.ini
Labels: enhancement

#1612 travis: remove secure variable
  .travis.yml
Labels: backport-stable-3.2, backport-stable-4.0, enhancement

#1614 travis: remove secure variable (bp #1612)
  .travis.yml
Labels: backport-stable-4.0

#1615 travis: remove secure variable (bp #1612)
  .travis.yml
Labels: backport-stable-3.2

#1616 contrib: add octopus to ceph/ceph repository
  contrib/ceph-build-config.sh
Labels: enhancement

#1617 tests/setup.yml: update the playbook
  tests/setup.yml
Labels: enhancement

#1623 ceph-releases: add centos-arm64/8 directory
  ceph-releases/ALL/centos-arm64/8/__DOCKERFILE_CLEAN_COMMON__
  ceph-releases/ALL/centos-arm64/8/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
  ceph-releases/ALL/centos-arm64/8/daemon-base/__GANESHA_PACKAGES__
  ceph-releases/ALL/centos-arm64/8/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos-arm64/8/daemon/__ETCD_PACKAGE__
  ceph-releases/ALL/centos-arm64/8/daemon/__KUBECTL_PACKAGE__
Labels: enhancement

#1620 octopus: nfs-ganesha bits from download.ceph.com
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0, enhancement

#1626 travis: remove branch limitation
  .travis.yml
Labels: enhancement

#1625 octopus: nfs-ganesha bits from download.ceph.com (bp #1620)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1627 tests: update ceph-ansible for octopus
  tests/tox.sh
  tox.ini
Labels: enhancement

#1628 ubi8: update to octopus
  ceph-releases/ALL/ubi8/daemon-base/__CSI_PACKAGES__
  contrib/compose-rhcs.sh
Labels: backport-stable-5.0, enhancement

#1629 ubi8: update to octopus (bp #1628)
  ceph-releases/ALL/ubi8/daemon-base/__CSI_PACKAGES__
  contrib/compose-rhcs.sh
Labels: backport-stable-5.0

#1634 octopus: ceph-iscsi bits from download.ceph.com
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0, enhancement

#1635 octopus: ceph-iscsi bits from download.ceph.com (bp #1634)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1637 tests: update ceph-ansible playbook name
  tests/tox.sh
Labels: backport-stable-5.0

#1638 tests: update ceph-ansible playbook name (bp #1637)
  tests/tox.sh
Labels: backport-stable-5.0
