Repository ceph/ceph-container, pull requests merged in 2020-02, with the labels that each got.

#1582 Fix activating legacy osd-disk partitioned nvme device
  src/daemon/osd_scenarios/osd_disk_activate.sh
Labels: backport-stable-4.0, bug

#1584 Fix activating legacy osd-disk partitioned nvme device (bp #1582)
  src/daemon/osd_scenarios/osd_disk_activate.sh
Labels: backport-stable-4.0

#1587 common_functions: fix lockbox partition number
  src/daemon/common_functions.sh
Labels: backport-stable-3.2, bug

#1588 common_functions: fix lockbox partition number (bp #1587)
  src/daemon/common_functions.sh
Labels: backport-stable-3.2

#1592 osd_volume_activate: umount lockbox after scanning
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-4.0, enhancement

#1597 osd_volume_activate: umount lockbox after scanning (bp #1592)
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-4.0
