Repository ceph/ceph-container, pull requests merged in 2020-04, with the labels that each got.

#1568 Sree: support python3
  .travis.yml
  src/daemon/Dockerfile
  src/daemon/Sree-0.1.tar.gz
  src/daemon/Sree-0.2.tar.gz
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#1642 contrib: Use newer version of podman when building CI containers
  contrib/build-push-ceph-container-imgs.sh
Labels: enhancement

#1643 Sree: support python3 (bp #1568)
  .travis.yml
  src/daemon/Dockerfile
  src/daemon/Sree-0.1.tar.gz
  src/daemon/Sree-0.2.tar.gz
Labels: backport-stable-5.0

#1641 tests/tox: run setup before the main playbook
  tests/tox.sh
Labels: backport-stable-5.0, enhancement

#1645 repo: Add configuration for stalebot
  .github/stale.yml
Labels: enhancement

#1644 tests/tox: run setup before the main playbook (bp #1641)
  tests/tox.sh
Labels: backport-stable-5.0

#1646 ubi8: add python3-saml package for mgr SSO module
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#1649 ubi8: update for RHCS 5
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_PREINSTALL__
  ceph-releases/ALL/ubi8/daemon/content_sets.yml
Labels: backport-stable-5.0

#1650 ubi8: update for RHCS 5 (bp #1649)
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_PREINSTALL__
  ceph-releases/ALL/ubi8/daemon/content_sets.yml
Labels: backport-stable-5.0

#1392 maint-lib/replace.py: use utf-8 decoding on file
  maint-lib/stagelib/replace.py
Labels: bug, do-not-close

#1652 tox: update ansible release to 2.9
  tox.ini
Labels: backport-stable-5.0, enhancement

#1654 tox: update ansible release to 2.9 (bp #1652)
  tox.ini
Labels: backport-stable-5.0

#1653 tests/tox.sh: increase pytest thread
  tests/tox.sh
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#1655 tests/tox.sh: increase pytest thread (bp #1653)
  tests/tox.sh
Labels: backport-stable-5.0

#1656 tests/tox.sh: increase pytest thread (bp #1653)
  tests/tox.sh
Labels: backport-stable-4.0

#1659 contrib: fix z release package regex
  contrib/ceph-build-config.sh
Labels: bug

#1662 daemon/README: add udev bind mount
  src/daemon/README.md
Labels: documentation
