Repository ceph/ceph-container, pull requests merged in 2020-01, with the labels that each got.

#1558 centos: add nfs-ganesha on CentOS 8
  ceph-releases/ALL/centos/8/daemon-base/__GANESHA_PACKAGES__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  src/daemon/demo.sh
  travis-builds/validate_demo_cluster.sh
Labels: enhancement

#1559 centos 8: add s3cmd package
  ceph-releases/ALL/centos/8/daemon/__S3CMD_PACKAGE__
  src/daemon/demo.sh
Labels: enhancement

#1569 centos8: don't remove /usr/lib/systemd
  ceph-releases/ALL/centos/8/__DOCKERFILE_CLEAN_COMMON__
Labels: enhancement

#1572 osd_volume_activate: open encrypted legacy parts
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-4.0, bug

#1575 add logging on the fly support (bp #1574)
  src/daemon/start_mon.sh
  src/daemon/variables_entrypoint.sh
Labels: backport-stable-4.0

#1576 start_mon: fix DAEMON_OPTS
  src/daemon/start_mon.sh
Labels: backport-stable-4.0, bug

#1577 start_mon: fix DAEMON_OPTS (bp #1576)
  src/daemon/start_mon.sh
Labels: backport-stable-4.0

#1580 ubi8: add nfs-ganesha-rados-urls package
  ceph-releases/ALL/ubi8/daemon-base/__GANESHA_PACKAGES__
Labels: backport-stable-4.0, bug

#1581 ubi8: add nfs-ganesha-rados-urls package (bp #1580)
  ceph-releases/ALL/ubi8/daemon-base/__GANESHA_PACKAGES__
Labels: backport-stable-4.0
