Repository ceph/ceph-container, pull requests merged in 2020-06, with the labels that each got.

#1685 centos: use repo at buildlogs.centos.org for nfs-ganesha
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: enhancement

#1686 centos: use https for ganesha repository
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, enhancement

#1687 centos: use https for ganesha repository (bp #1686)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1688 centos: use https for ganesha repository (bp #1686)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0

#1689 centos: use https for ganesha repository (bp #1686)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-3.2

#1690 tests/tox: update ius centos repository
  tests/tox.sh
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, enhancement

#1691 tests/tox: update ius centos repository (bp #1690)
  tests/tox.sh
Labels: backport-stable-5.0

#1692 tests/tox: update ius centos repository (bp #1690)
  tests/tox.sh
Labels: backport-stable-4.0

#1693 tests/tox: update ius centos repository (bp #1690)
  tests/tox.sh
Labels: backport-stable-3.2

#1684 osd_volume_activate: support ceph-disk based OSDs via ceph-volume
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: feature

#1696 contrib: update flavors/releases list
  .travis.yml
  Makefile
  contrib/build-push-ceph-container-imgs-arm64.sh
  contrib/build-push-ceph-container-imgs.sh
  contrib/ceph-build-config.sh
Labels: enhancement

#1694 centos/8: remove copr and sepia repositories
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0, enhancement

#1698 centos/8: remove copr and sepia repositories (bp #1694)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1700 demo: fix no redundancy for nautilus
  src/daemon/start_mon.sh
Labels: backport-stable-4.0, backport-stable-5.0

#1701 demo: fix no redundancy for nautilus (bp #1700)
  src/daemon/start_mon.sh
Labels: backport-stable-5.0

#1699 centos: update nfs-ganesha to 3.3
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0, enhancement

#1703 centos: update nfs-ganesha to 3.3 (bp #1699)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0
