Repository ceph/ceph-container, pull requests merged in 2020-05, with the labels that each got.

#1664 contrib: update commit-rhcs.sh for octopus
  contrib/commit-rhcs.sh
Labels: backport-stable-5.0

#1665 contrib: update commit-rhcs for octopus (bp #1664)
  contrib/commit-rhcs.sh
Labels: backport-stable-5.0

#1669 ubi8: ignore absent pulp repositories
  ceph-releases/ALL/ubi8/daemon/container.yaml
Labels: backport-stable-5.0, enhancement

#1670 ubi8: ignore absent pulp repositories (bp #1669)
  ceph-releases/ALL/ubi8/daemon/container.yaml
Labels: backport-stable-5.0

#1674 manifest: add variant attribute to arm64 build
  contrib/build-push-ceph-container-imgs.sh
  contrib/ceph-build-config.sh
Labels: enhancement

#1678 ubi8: add s390x entry to content_sets.yml
  ceph-releases/ALL/ubi8/daemon/content_sets.yml
Labels: backport-stable-5.0

#1679 ubi8: add s390x entry to content_sets.yml (bp #1678)
  ceph-releases/ALL/ubi8/daemon/content_sets.yml
Labels: backport-stable-5.0

#1680 ubi8: add s390x entry to content_sets.yml (bp #1678)
  ceph-releases/ALL/ubi8/daemon/content_sets.yml
Labels: backport-stable-4.0
