Repository ceph/ceph-container, pull requests merged in 2021-01, with the labels that each got.

#1776 [skip ci] daemon/osd_directory: fix OSD keyring permission
  src/daemon/osd_scenarios/osd_directory.sh
Labels: backport-stable-4.0, backport-stable-5.0, bug

#1778 [skip ci] daemon/osd_directory: fix OSD keyring permission
  src/daemon/osd_scenarios/osd_directory.sh
Labels: backport-stable-4.0

#1780 [skip ci] daemon/demo: avoid duplicate option on restart
  src/daemon/start_mon.sh
Labels: backport-stable-4.0, backport-stable-5.0, bug

#1781 [skip ci] daemon/demo: avoid duplicate option on restart (bp #1780)
  src/daemon/start_mon.sh
Labels: backport-stable-5.0

#1782 [skip ci] daemon/demo: avoid duplicate option on restart (bp #1780)
  src/daemon/start_mon.sh
Labels: backport-stable-4.0

#1787 tests/tox: increase pytest rerun delay
  tests/tox.sh
Labels: backport-stable-4.0, backport-stable-5.0, enhancement, tests

#1788 tests/tox: increase pytest rerun delay (bp #bp1787)
  tests/tox.sh
Labels: backport-stable-5.0

#1786 daemon-base: add support for cephfs-mirror package
  ceph-releases/ALL/ubi8/daemon-base/__CEPHFS_PACKAGES__
  ceph-releases/nautilus/daemon-base/__CEPHFS_PACKAGES__
  ceph-releases/octopus/daemon-base/__CEPHFS_PACKAGES__
  src/daemon-base/__CEPHFS_PACKAGES__
  src/daemon-base/__CEPH_BASE_PACKAGES__
Labels: feature

#1789 tests/tox: increase pytest rerun delay (bp #1787)
  tests/tox.sh
Labels: backport-stable-4.0

#1790 test/tox: remove fetch_directory ansible variable
  tests/tox.sh
Labels: backport-stable-4.0, backport-stable-5.0, tests

#1792 test/tox: remove fetch_directory ansible variable (bp #1790)
  tests/tox.sh
Labels: backport-stable-5.0

#1793 test/tox: remove fetch_directory ansible variable (bp #1790)
  tests/tox.sh
Labels: backport-stable-4.0

#1795 release: add pacific target
  Makefile
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: feature

#1796 [skip ci] contrib: build pacific devel on x86_64
  contrib/build-push-ceph-container-imgs.sh
Labels: feature

#1783 osd_activate: fix osd umount on container stop
  src/daemon/osd_scenarios/osd_disk_activate.sh
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, bugzilla

#1800 osd_activate: fix osd umount on container stop (bp #1783)
  src/daemon/osd_scenarios/osd_disk_activate.sh
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-5.0

#1801 osd_activate: fix osd umount on container stop (bp #1783)
  src/daemon/osd_scenarios/osd_disk_activate.sh
  src/daemon/osd_scenarios/osd_volume_activate.sh
Labels: backport-stable-5.0

#1798 [skip ci] ubi8: disable weak dependencies
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
Labels: bugzilla

#1803 [skip ci] contrib: add back luminous on centos 7
  contrib/build-push-ceph-container-imgs.sh
Labels: bug
