Repository ceph/ceph-container, pull requests merged in 2021-09, with the labels that each got.

#1940 contrib/rhcs: set upstream branch explicitly
  contrib/commit-rhcs.sh
Labels: backport-stable-4.0, backport-stable-5.0, RHCS, backport-stable-6.0

#1941 [skip ci] contrib/rhcs: set upstream branch explicitly (bp #1940)
  contrib/commit-rhcs.sh
Labels: backport-stable-6.0

#1942 [skip ci] contrib/rhcs: set upstream branch explicitly (bp #1940)
  contrib/commit-rhcs.sh
Labels: backport-stable-5.0

#1943 [skip ci] contrib/rhcs: set upstream branch explicitly (bp #1940)
  contrib/commit-rhcs.sh
Labels: backport-stable-4.0

#1944 [skip ci] contrib/rhcs: set upstream branch explicitly (bp #1940)
  contrib/commit-rhcs.sh
Labels: backport-stable-3.2

#1945 Revert "ubi8: ignore absent pulp repositories"
  ceph-releases/ALL/ubi8/daemon/container.yaml
Labels: RHCS, backport-stable-6.0

#1946 [skip ci] Revert "ubi8: ignore absent pulp repositories"
  ceph-releases/ALL/ubi8/daemon/container.yaml
Labels: backport-stable-6.0

#1951 [skip ci] contrib: update quay api pagination parameter
  contrib/build-push-ceph-container-imgs.sh
  contrib/ceph-build-config.sh
Labels: enhancement

#1953 centos/arm: add python3-saml package
  ceph-releases/ALL/centos-arm64/8/daemon-base/__CEPH_MGR_PACKAGES__
Labels: enhancement, backport-stable-5.0, backport-stable-6.0

#1954 [skip ci][stable-6.0] centos/arm: add python3-saml package
  ceph-releases/ALL/centos-arm64/8/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-6.0

#1955 [skip ci][stable-5.0] centos/arm: add python3-saml package
  ceph-releases/ALL/centos-arm64/8/daemon-base/__CEPH_MGR_PACKAGES__
Labels: backport-stable-5.0
