Repository ceph/ceph-container, pull requests merged in 2021-03, with the labels that each got.

#1816 [skip ci] demo/validation: fix mds cluster status check
  travis-builds/validate_demo_cluster.sh
Labels: bug

#1820 [skip ci] demo/validation: fix mds cluster status check
  travis-builds/validate_demo_cluster.sh
Labels: backport-stable-6.0

#1821 daemon-base: add copr repo for python3-scikit-learn packages
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0, backport-stable-6.0, feature

#1823 centos-arm64: fix gperftools libs file
  ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__
Labels: backport-stable-5.0, backport-stable-6.0, bug

#1824 [skip ci] centos-arm64: fix gperftools libs file (bp #1823)
  ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__
Labels: backport-stable-6.0

#1825 [skip ci] centos-arm64: fix gperftools libs file (bp #1823)
  ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__
Labels: backport-stable-5.0

#1827 daemon-base: install python3-scikit-learn on el8
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-6.0

#1828 daemon-base: install python3-scikit-learn on el8
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1822 CI builds: push -aarch64 versions of short tags; improve "kubic" repo handling
  contrib/build-push-ceph-container-imgs.sh
Labels: enhancement

#1829 centos/pacific: use ganesha from download.ceph.com
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-6.0, enhancement

#1815 fix: small error
  src/daemon/README.md
Labels: documentation

#1830 centos/pacific: use ganesha from download.ceph.com (bp #1829)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-6.0

#1826 tests: increase reruns and reruns delay in pytest
  tests/tox.sh
Labels: backport-stable-4.0

#1831 Revert "gperftools: install from epel-testing"
  ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos/8/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__GPERFTOOLS_LIBS__
Labels: backport-stable-5.0, backport-stable-6.0

#1832 Revert "gperftools: install from epel-testing" (bp #1831)
  ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos/8/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__GPERFTOOLS_LIBS__
Labels: backport-stable-6.0

#1833 Revert "gperftools: install from epel-testing" (bp #1831)
  ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos/8/daemon-base/__GPERFTOOLS_LIBS__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__GPERFTOOLS_LIBS__
Labels: backport-stable-5.0

#1835 [skip ci] contrib: Unmask docker service if needed
  contrib/build-push-ceph-container-imgs.sh
  contrib/ceph-build-config.sh
Labels: enhancement

#1839 [skip ci] daemon-base/centos: specify arch for tcmu url
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#1840 [skip ci] daemon-base/centos: specify arch for tcmu url (bp #1839)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-6.0

#1841 [skip ci] daemon-base/centos: specify arch for tcmu url (bp #1839)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1842 [skip ci] daemon-base/centos: specify arch for tcmu url (bp #1839)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0

#1838 [skip ci] daemon-base: add `ceph-immutable-object-cache` package
  ceph-releases/nautilus/daemon-base/__CEPH_IMMUTABLE_OBJECT_CACHE_PACKAGE__
  ceph-releases/octopus/daemon-base/__CEPH_IMMUTABLE_OBJECT_CACHE_PACKAGE__
  src/daemon-base/__CEPH_BASE_PACKAGES__
  src/daemon-base/__CEPH_IMMUTABLE_OBJECT_CACHE_PACKAGE__
Labels: backport-stable-6.0, bugzilla

#1844 [skip ci] daemon-base: add missing env var to immutable pkg
  src/daemon-base/__CEPH_IMMUTABLE_OBJECT_CACHE_PACKAGE__
Labels: backport-stable-6.0, bug

#1845 [skip ci] daemon-base: move scikit learn to the main install
  ceph-releases/ALL/centos-arm64/8/daemon-base/__SCIKIT_LEARN__
  ceph-releases/ALL/centos-arm64/daemon-base/__SCIKIT_LEARN__
  ceph-releases/ALL/centos/8/daemon-base/__SCIKIT_LEARN__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__SCIKIT_LEARN__
  src/daemon-base/__CEPH_BASE_PACKAGES__
Labels: backport-stable-5.0, backport-stable-6.0, enhancement

#1849 [skip ci] daemon-base: move scikit learn to the main install (bp #1845)
  ceph-releases/ALL/centos-arm64/8/daemon-base/__SCIKIT_LEARN__
  ceph-releases/ALL/centos-arm64/daemon-base/__SCIKIT_LEARN__
  ceph-releases/ALL/centos/8/daemon-base/__SCIKIT_LEARN__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__SCIKIT_LEARN__
  src/daemon-base/__CEPH_BASE_PACKAGES__
Labels: backport-stable-6.0

#1850 [skip ci] daemon-base: move scikit learn to the main install (bp #1845)
  ceph-releases/ALL/centos-arm64/8/daemon-base/__SCIKIT_LEARN__
  ceph-releases/ALL/centos-arm64/daemon-base/__SCIKIT_LEARN__
  ceph-releases/ALL/centos/8/daemon-base/__SCIKIT_LEARN__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__SCIKIT_LEARN__
  src/daemon-base/__CEPH_BASE_PACKAGES__
Labels: backport-stable-5.0

#1851 [skip ci] daemon-base/centos: simplify tcmu shaman repo code
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#1853 [skip ci] daemon-base/centos: simplify tcmu shaman repo code (bp #1851)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-6.0

#1854 [skip ci] daemon-base/centos: simplify tcmu shaman repo code (bp #1851)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1855 [skip ci] daemon-base/centos: simplify tcmu shaman repo code (bp #1851)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0

#1852 [skip ci] workflow: add arm64 container build
  .github/workflows/container.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, feature

#1856 [skip ci] workflow: add arm64 container build (bp #1852)
  .github/workflows/container.yml
Labels: backport-stable-6.0

#1857 [skip ci] workflow: add arm64 container build (bp #1852)
  .github/workflows/container.yml
Labels: backport-stable-5.0

#1858 [skip ci] workflow: add arm64 container build (bp #1852)
  .github/workflows/container.yml
Labels: backport-stable-4.0

#1859 [skip ci] centos/daemon-base: do not use BASEOS_REPO env var
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#1861 [skip ci] centos/daemon-base: do not use BASEOS_REPO env var (bp #1859)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-6.0

#1862 [skip ci] centos/daemon-base: do not use BASEOS_REPO env var (bp #1859)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1863 [skip ci] centos/daemon-base: do not use BASEOS_REPO env var (bp #1859)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0

#1846 [skip ci] centos-arm64/8: enable ceph-iscsi packages
  ceph-releases/ALL/centos-arm64/8/daemon-base/__ISCSI_PACKAGES__
Labels: backport-stable-5.0, backport-stable-6.0, feature

#1864 [skip ci] centos-arm64/8: enable ceph-iscsi packages (bp #1846)
  ceph-releases/ALL/centos-arm64/8/daemon-base/__ISCSI_PACKAGES__
Labels: backport-stable-6.0

#1865 [skip ci] centos-arm64/8: enable ceph-iscsi packages (bp #1846)
  ceph-releases/ALL/centos-arm64/8/daemon-base/__ISCSI_PACKAGES__
Labels: backport-stable-5.0

#1860 [skip ci] centos/daemon-base: enable gpgcheck on nfs-ganesha
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#1866 [skip ci] centos/daemon-base: enable gpgcheck on nfs-ganesha (bp #1860)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-6.0

#1867 [skip ci] centos/daemon-base: enable gpgcheck on nfs-ganesha (bp #1860)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1868 [skip ci] centos/daemon-base: enable gpgcheck on nfs-ganesha (bp #1860)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0
