Repository ceph/ceph-container, pull requests merged in 2021-05, with the labels that each got.

#1875 [skip ci] README.md: update ceph doc URLs
  src/daemon/README.md
Labels: documentation

#1890 centos/ubi: disable weak dependencies
  ceph-releases/ALL/centos/8/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#1892 [skip ci] centos/ubi: disable weak dependencies (bp #1890)
  ceph-releases/ALL/centos/8/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-6.0

#1893 [skip ci] centos/ubi: disable weak dependencies (bp #1890)
  ceph-releases/ALL/centos/8/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-5.0

#1894 [skip ci] centos/ubi: disable weak dependencies (bp #1890)
  ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/centos/daemon/__DOCKERFILE_INSTALL__
  ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
Labels: backport-stable-4.0

#1895 [skip ci] daemon: fix confd ceph template
  src/daemon/confd/templates/ceph.conf.tmpl
Labels: backport-stable-5.0, backport-stable-6.0, bug

#1896 [skip ci] daemon: fix confd ceph template (bp #1895)
  src/daemon/confd/templates/ceph.conf.tmpl
Labels: backport-stable-6.0

#1897 [skip ci] daemon: fix confd ceph template (bp #1895)
  src/daemon/confd/templates/ceph.conf.tmpl
Labels: backport-stable-5.0
